name: Run every day at 00:00 UTC

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  cron:
    name: Run every day
    runs-on: ubuntu-latest

    steps:
      - name: Hello world (cron)
        run: echo "Hello world (cron)"
        
