name: PR Verify

on:
  pull_request: 
    branches: [ "main" ]
env:
  API_CSPROJ_PATH: "./src/GithubActionsDotNet.Api/GithubActionsDotNet.Api.csproj"

jobs:
  secrets:
    name: Secrets demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "secrets"

    steps:
      - name: echo environment variable
        run: echo "THe value of $JOB_NAME is $API_CSPROJ_PATH"

  new_job:
    name: Secrets demo job 2
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "new job"

    steps:
      - name: echo environment variable
        run: echo "THe value of $JOB_NAME is $API_CSPROJ_PATH"        