name: PR Verify

on:
  pull_request: 
    branches: [ "main" ]
env:
  API_CSPROJ_PATH: "./src/GithubActionsDotNet.Api/GithubActionsDotNet.Api.csproj"

jobs:
  secrets:
    name: Secrets demo
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variable
        run: echo "THe value of SECRET_API_KEY is ${{ secrets.SECRET_API_KEY }}"